/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ConfessionRoom } from "./ConfessionRoom";
export * as factories from "./factories";
export { ConfessionRoom__factory } from "./factories/ConfessionRoom__factory";
